[package]
name = "audi8"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-cors = "0.7.1"
actix-web = "4.11.0"
clap = { version = "4.5.47", features = ["derive"] }
env_logger = "0.11.8"
hound = "3.5.1"
rubato = "0.16.2"
serde = "1.0.226"
